# Generated by Django 5.1 on 2024-08-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('groceries', 'Groceries'), ('transportation', 'Transportation'), ('others', 'Others')], max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
