# Generated by Django 5.1 on 2024-09-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_emailfilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailfilter',
            name='user',
        ),
    ]
