# Generated by Django 5.1 on 2024-09-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_emailfilter_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailfilter',
            old_name='sender',
            new_name='vendor',
        ),
    ]
